INHERIT: docs/shared/mkdocs-base.yml

watch:
  - README.md
  - CHANGELOG.md

repo_url: https://github.com/numfocus/MOSS

theme:
  features:
    # left blank intentionally

markdown_extensions:
  mkdocs-click: {}

nav:
  - Overview: index.md
  - User Guide: user_guide/
  - CLI: cli.md
  - Code Reference: reference/ # generated code reference
  - Decisions: decisions/
  - Changelog: changes.md

plugins:
  - gen-files:
    scripts:
      - docs/gen_ref_pages.py
  - mkdocs-strings
  - section-index

